input {
	kb_options = caps:escape,ctrl:swap_lalt_lctl
	accel_profile = flat
	force_no_accel = true
	sensitivity = 1.0
	follow_mouse = 1
	float_switch_override_focus = 0
	touchpad {
		natural_scroll = true
	}
}

cursor {
	no_hardware_cursors = true
	min_refresh_rate = 60
	no_warps = false
	hotspot_padding = 0
	inactive_timeout = 0
}

render {
	direct_scanout = true
}

misc {
	mouse_move_enables_dpms = false
}

animations {
	enabled = false
}
