bind = Super, w, exec, google-chrome-stable
bind = SUPER CTRL, l, resizeactive, 150 0
bind = SUPER CTRL, h, resizeactive, -150 0
bind = SUPER CTRL, k, resizeactive, 0 -150
bind = SUPER CTRL, j, resizeactive, 0 150
bind = SUPER, l, movefocus, r
bind = SUPER, h, movefocus, l
bind = SUPER, k, movefocus, u
bind = SUPER, j, movefocus, d
bind = SUPER SHIFT, l, swapwindow, r
bind = SUPER SHIFT, h, swapwindow, l
bind = SUPER SHIFT, k, swapwindow, u
bind = SUPER SHIFT, m, swapwindow, d
bind = SUPER, X, killactive

bind = SUPER CTRL, s, exec, hyprlock
bind = SUPER, o, exec, flatpak run md.obsidian.Obsidian --ozone-platform-hint=auto --enable-features=WaylandWindowDecorations
bind = SUPER, i, exec, burpsuite
